version: "3"
services:
    backend:
        build:
            context: .
            target: dev
        container_name: chankari-backend
        volumes:
            - ./:/app/src
        ports:
            - 8085:8085
        tty: true
