version: "3"
services:
    backend:
        build:
            context: .
            target: dev
        container_name: chankari-backend
        volumes:
            - ./:/app/src
        working_dir: /app/src
        ports:
            - 8000:8000
        environment:
            - WATCHFILES_FORCE_POLLING=true
        tty: true
