FROM node:14.17.5

ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo
Run npm install -g npm
RUN npm install react-router-dom
#RUN npm audit fix
RUN npm install react-bootstrap bootstrap

WORKDIR /usr/src/app/frontend/
#WORKDIR /usr/src/app/
