openapi: 3.0.0
info:
  title: chan-kari API
  description: WIP
  version: 1.0.0
servers:
  - url: http://{host}:{port}/api/{version}/
    description: For local
    variables:
      host:
        default: localhost
      port:
        default: "8080"
      version:
        default: v1
components:
  securitySchemes:
    token:
      type: apiKey
      name: token
      in: header
      description: ID token obtained from FireBase
paths:
  /users/profile:
    $ref: "path/users.profile.yaml"
  /items:
    $ref: "path/items.yaml#/paths/itemList"
  /items/{itemId}:
    $ref: "path/items.yaml#/paths/itemDetail"
  /users/items:
    $ref: "path/users.items.yaml#/paths/itemList"
  /users/items/{itemId}:
    $ref: "path/users.items.yaml#/paths/itemDetail"
  /users/rentals:
    $ref: "path/users.rentals.yaml#/paths/rentalList"
  /users/rentals/{rentalId}:
    $ref: "path/users.rentals.yaml#/paths/rentalDetail"
  /users/rentals/{rentalId}/return:
    $ref: "path/users.rentals.yaml#/paths/rentalReturn"
