openapi: 3.0.0
info:
  title: chan-kari API
  description: WIP
  version: 1.0.0
servers:
  - url: http://{host}:{port}/api/
    description: For development
    variables:
      host:
        default: localhost
      port:
        default: "8080"
paths:
  /test:
    get:
      summary: test
      description: test
      responses:
        "200":
          description: test
