openapi: 3.0.0
info:
  title: chan-kari API
  description: WIP
  version: 1.0.0
servers:
  - url: http://{host}:{port}/api/{version}/
    description: For local
    variables:
      host:
        default: localhost
      port:
        default: "8080"
      version:
        default: v1
components:
  securitySchemes:
    token:
      type: apiKey
      name: token
      in: header
      description: ID token obtained from FireBase

paths:
  /test:
    get:
      summary: test
      description: test
      responses:
        "200":
          description: test
